### PR TITLE
Add defvar to get rid of compilation warning

### PR DESCRIPTION
**Pull request by cute-jumper**

### CODE REVIEW

**Comment by RenWenshan** [comment]
@cute-jumper could you provide a description for this? What compilation warning are you trying to get rid of?

**Comment by cute-jumper** [comment]
You use `moz-controller-repl-output-tag` in your `moz-controller-repl-filter` but you don't define it before, so the compiler will issue an warning about using the free variable `moz-controller-repl-output-tag`.

**UNRELATED TO THIS PULL REQUEST**:
Just to let you know, I found this package really interesting. I rewrote the code and add many features and bug fixes to it. The code is quite different from what you have right now. You can take a look at it in the `dev' branch of my fork repo:
https://github.com/cute-jumper/emacs-moz-controller/tree/dev

The code is almost done, but I haven't documented it yet. I haven't decided how to do with the new package, so maybe I should ask your opinions first.  I intend to make it a different package instead of creating a new pull request since many things are changed.

Many thanks for creating this package!

**Comment by RenWenshan** [comment]
@cute-jumper glad to know it's helpful. 

It's totally up to you whether to create a new package or add the changes to the current one -- I can pull your changes anyway. Will take a look at your branch at some point this week, happy hacking :+1:

**Comment by cute-jumper** [comment]
Hi Wenshan, 

I created a new repo here:
https://github.com/cute-jumper/emacs-firefox-controller

You can take a look!

**Pull request merged**
